### ISSUE TITLE
(Question) AAdecode : Website API or C# conversion?

### ISSUE THREAD

**Issue by MrArca9** [cat-in-136/cat-in-136.github.io#2]
I have an application i am trying to get aadecode working with, but i can't for the life of me convert the js/php/VB to c# to use it, and i don't see a way of passing post data to the site for give and take.

Any chance of doing either of these? Please and thank you <3

**Comment by cat-in-136** [comment]
How about using https://www.npmjs.com/package/aadecode-cli ?


Note: my aadecode code depends on JavaScript eval function. So I think it's is difficult to convert my code to C#.

**Comment by MrArca9** [comment]
That's alright, i knew that eval was going to be difficult to transcode, if at all. 
Was wondering if it was possible to do something where you can do ?AADecodeString=xxxx for a php or api call? Don't know if github would support it but, would make my life easier to do a post and retrieve a string.

**Comment by cat-in-136** [comment]
I think it is difficult my code to *any other* language than JavaScript. So, I recommend `npm install aadecode-cli` and use it.

You had better write your own code if you don't want to use aadecode-cli. I wrote the post "[code reading : javascript code encoded as aaencode](https://cat-in-136.github.io/2010/11/code-reading-aaencoded-javascript-code.html)" in my blog, which would be helpful for you.

**Comment by MrArca9** [comment]
Thanks for the help! Will use these.
